env:
  node: true
  es2021: true
  jest: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: warn
  no-magic-numbers: error
  no-unused-vars: warn
